# Generated by Django 4.1.7 on 2023-03-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockvuser',
            name='wallet',
            field=models.FloatField(default=1000, max_length=8),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
