# Generated by Django 4.1.7 on 2023-04-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockV', '0003_alter_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownedcoins',
            old_name='coin_symbol',
            new_name='coin_name',
        ),
    ]
