# Generated by Django 4.1.3 on 2022-12-20 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockV', '0003_remove_user_is_active_remove_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockvuser',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockV.wallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.FloatField(default=1000, max_length=30),
        ),
    ]
