# Generated by Django 4.1.7 on 2023-03-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockV', '0004_alter_stockvuser_wallet_alter_wallet_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='dailyChange',
            field=models.FloatField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name='coin',
            name='price',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='coin',
            name='symbol',
            field=models.CharField(default='TEST', max_length=10),
            preserve_default=False,
        ),
    ]
