# Generated by Django 4.1.7 on 2023-03-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockV', '0005_coin_dailychange_coin_price_coin_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='tradeSymbol',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
