# Generated by Django 4.1.7 on 2023-03-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockV', '0006_coin_tradesymbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='tradeSymbol',
        ),
    ]
